### ISSUE TITLE
http errors != 401 are not catched in get_missing_files() and cause gramps to terminate

### ISSUE THREAD

**Issue by ondrno** [DavidMStraub/gramps-web-sync#11]
Environment: grampsweb 0.17, websync plugin (as of 08.12.2022)

Steps to reproduce:
1) start grampsweb
2) start gramps with websync plugin
3) do sync until it comes to Media Files
4) let the grampsweb return an http error 500 -> gramps will be terminated because the http error is raised in get_missing_files(), line 139 (see attached screenshot)

![Screenshot from 2022-12-08 20-08-10](https://user-images.githubusercontent.com/33825732/206548408-a9bf0a33-70c9-4ab1-8e45-a81cfcee1ae9.png)

**Comment by teitrand** [comment]
I get this error too.

**Comment by DavidMStraub** [comment]
Hi,

I forgot about this issue.

That this method raises is intentional, the error handling should be done in `webapisync.py`. However, I am puzzled why you are getting a 500 in the first place. `get_missing_files` is supposed to check which files are present, so it should not choke on files being absent (which is a common cause of 500s). Can you please check the API server log, so we can identify the root cause?

Thanks!

**Comment by teitrand** [comment]
It happens only with HTTP with no SSL and website only accessible on port 80. With https the error clears.

Sendt fra Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DavidMStraub** [comment]
I also ran into this issue now with media hosted on S3 https://github.com/gramps-project/gramps-webapi/issues/361
