### ISSUE TITLE
Unhandled exception while syncing to Gramps Web API

### ISSUE THREAD

**Issue by jonade** [DavidMStraub/gramps-web-sync#22]
I'm getting unhandled exceptions within the Gramps Web Sync plugin when attempting to sync to a selfhosted version of Gramps Web. Checked that I'm running the latest version of the plugin, and confirmed that reopening the client doesn't help with resolving.

Error Details: 
===================

16815: WARNING: dummydb.py: line 1420: database is closed
37441: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Roaming\gramps\gramps51\plugins\GrampsWebSync\grampswebsync.py", line 368, in get_diff_actions
    path.unlink()  # delete temporary file
AttributeError: 'NoneType' object has no attribute 'unlink'

System Information: 
===================

Gramps version: AIO64-5.1.6-1 
Python version: 3.6.4 (default, Jan 23 2018, 13:17:37)  [GCC 7.2.0 64 bit (AMD64)] 
BSDDB version: 6.1.0 (6, 0, 30) 
sqlite version: 3.21.0 (2.6.0) 
LANG: en_GB.UTF-8
OS: Windows

GTK version    : 3.18.9
gobject version: 3.26.1
cairo version  : (1, 16, 1)

There is also another person reporting this at https://gramps-project.org/bugs/view.php?id=13066

**Comment by DavidMStraub** [comment]
Hi,

I doubt that this is the latest version because that's not what line 368 looks like.

Have you installed the development version from this repository? Unfortuntely the version in the official addon repository is not updated very frequently.

If not, please install the development version manually and let me know if the error is gone.

**Comment by jonade** [comment]
Ok, well to phrase differently, that's the latest version from the addon repository.

I can update to the dev version and the error goes away. I can't say that I'm really a fan of managing plugins manually though.

Presumably there have been recent changes to the grampsweb api that are incompatible with the older version in the addon repository. Anyway, we can close this, but it's seeming to be affecting other people also.

**Comment by DavidMStraub** [comment]
> I can update to the dev version and the error goes away. I can't say that I'm really a fan of managing plugins manually though.

I agree, but unfortunately the merging of pull requests at addons-source takes too long. I will create one this week, let's hope it gets merged faster this time.

> Presumably there have been recent changes to the grampsweb api that are incompatible with the older version in the addon repository. Anyway, we can close this, but it's seeming to be affecting other people also.

No, I don't think so, but bugs in the addon that have been fixed.

**Comment by Rick603** [comment]
Hi, I am the person that reported this bug over on the gramps.project.org site. I used the bug reporting link in the app, which took me there, although I do now realize it really wasn't the correct place to report it - please let me know if I should repost that report in the bug tracker here.  

I just looked back, and I experienced the bug with a development version of the sync plugin that I had pulled about a month ago (9/22/2023 to be precise). For me, the bug is a one-shot deal - I get the error, but if I just try it again, it works on the second try. Please advise if you want me to pull a more current Dev release, or wait for you to request that merge?

**Comment by Rick603** [comment]
Looking more closely, it looks like I may have erred on installing the Dev version of the plugin - please stand by while I check further on that...

**Comment by Rick603** [comment]
I also corrected my issue by properly installing the Dev version of the plugin - not quite sure how I goofed that up on the first attempt, but it is working properly for me now - from my perspective, bug is resolved in the current Dev release.

**Comment by jonade** [comment]
Thanks for your help in merging this to the addon repo. I'll close this off now.
