### ISSUE TITLE
Documentation (README.md) updates

### ISSUE THREAD

**Issue by emyoulation** [DavidMStraub/gramps-web-sync#8]
Please add a screen capture to the README.me

![image](https://user-images.githubusercontent.com/69127217/202765720-d2dbef46-c121-4097-82b0-9c0816f47cf8.png)

also, the diocumented menu label doesn't match the GUI.  The Submenu item reads:  "Gramps Web Sync"
![image](https://user-images.githubusercontent.com/69127217/202768558-7ce5182e-43ce-45dc-aac8-72a50bb20812.png)

**Comment by emyoulation** [comment]
The docs show:
> **Gramps Web API Sync Addon**
> 
> Development version of a [Gramps](https://gramps-project.org/blog/) addon to synchronize a local family tree with a [Gramps Web API](https://github.com/gramps-project/gramps-webapi/) instance

The link does not point to the Gramps Web folder with the setup doc.  Are **Gramps Web API** and **Gramps Web** different things?  If so, could you add the link to Gramps Web. And some differentiating text would be helpful.

**Comment by DavidMStraub** [comment]
You are right, but I would prefer having the pull request in addons-source merged, adding updated documentation in Gramps Wiki, and closing this repository.

The addon was originally called Web API Sync since it interacts directly with the Web API ([here is an explanation of the difference](https://gramps-project.github.io/web/dev-backend/)) but I renamed it since these architectural subtleties are confusing to end users.

**Comment by DavidMStraub** [comment]
This repo and the Readme will be archived, documentation updates will be done at grampsweb.org.
